#!/usr/bin/env python3
"""Bake a PSF console font into a C array for the kernel framebuffer console.

Usage:
    python3 tools/genfont.py <font.psf.gz> <out.c> <out.h>

Works with PSF1 and PSF2, 8x16.  On Arch these live in
/usr/share/kbd/consolefonts/ (e.g. default8x16.psfu.gz).  Swap fonts by
re-running this script - don't try to parse a TTF in the kernel.
"""
import gzip
import pathlib
import sys

WIDTH, HEIGHT = 8, 16
GLYPHS = 256


def load_psf(path):
    data = gzip.open(path, "rb").read() if str(path).endswith(".gz") else pathlib.Path(path).read_bytes()

    if data[:2] == b"\x36\x04":  # PSF1
        mode, charsize = data[2], data[3]
        count = 512 if (mode & 0x01) else 256
        if mode & 0x02:
            pass  # has a unicode table; it follows the glyph data, ignore it
        width, height = 8, charsize
        offset = 4
    elif data[:4] == b"\x72\xb5\x4a\x86":  # PSF2
        _, headersize, _flags, count, charsize, height, width = (
            int.from_bytes(data[4:8], "little"),
            int.from_bytes(data[8:12], "little"),
            int.from_bytes(data[12:16], "little"),
            int.from_bytes(data[16:20], "little"),
            int.from_bytes(data[20:24], "little"),
            int.from_bytes(data[24:28], "little"),
            int.from_bytes(data[28:32], "little"),
        )
        offset = headersize
    else:
        raise SystemExit(f"{path}: not a PSF font (magic {data[:4].hex()})")

    if (width, height) != (WIDTH, HEIGHT):
        raise SystemExit(f"{path}: expected {WIDTH}x{HEIGHT}, got {width}x{height}")
    if count < GLYPHS:
        raise SystemExit(f"{path}: only {count} glyphs, need {GLYPHS}")

    stride = (width + 7) // 8
    glyphs = []
    for g in range(GLYPHS):
        start = offset + g * charsize
        glyphs.append(data[start:start + stride * height])
    return glyphs


def emit(glyphs, font_name, source):
    lines = []
    lines.append("/* Generated by tools/genfont.py from %s - do not edit by hand. */" % source)
    lines.append("#include <kernel/devices/font8x16.h>")
    lines.append("")
    lines.append("const uint8_t font8x16[FONT8X16_GLYPHS][FONT8X16_BYTES] = {")
    for i, g in enumerate(glyphs):
        row = ", ".join("0x%02x" % b for b in g)
        printable = chr(i) if 0x20 <= i < 0x7F else "."
        lines.append("\t{ %s }, /* 0x%02x '%s' */" % (row, i, printable))
    lines.append("};")
    lines.append("")
    return "\n".join(lines)


HEADER = """#pragma once

/* 8x16 console font, one byte per pixel row, MSB = leftmost pixel.
 * Regenerate with: python3 tools/genfont.py <font.psf.gz> <out.c> <out.h>
 */

#include <stdint.h>

#define FONT8X16_W 8
#define FONT8X16_H 16
#define FONT8X16_GLYPHS 256
#define FONT8X16_BYTES 16

extern const uint8_t font8x16[FONT8X16_GLYPHS][FONT8X16_BYTES];
"""


def main() -> int:
    if len(sys.argv) != 4:
        print(__doc__)
        return 2
    src, out_c, out_h = sys.argv[1], pathlib.Path(sys.argv[2]), pathlib.Path(sys.argv[3])
    glyphs = load_psf(src)
    out_c.parent.mkdir(parents=True, exist_ok=True)
    out_h.parent.mkdir(parents=True, exist_ok=True)
    out_c.write_text(emit(glyphs, "font8x16", pathlib.Path(src).name))
    out_h.write_text(HEADER)
    print(f"{out_h}: {GLYPHS} glyphs, {WIDTH}x{HEIGHT}")
    print(f"{out_c}: {out_c.stat().st_size} bytes")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
